Resources:
  AWSPrivateNetworkAWSVpcE0F4E4E3:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.16.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: private-aws-network
    Metadata:
      aws:cdk:path: CdkHybridArchitectureDemoStack/AWSPrivateNetwork/AWSVpc/Resource
  AWSPrivateNetworkAWSVpcPrivateSubnetASubnetC2333EDC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: AWSPrivateNetworkAWSVpcE0F4E4E3
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      CidrBlock: 10.16.32.0/20
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: CdkHybridArchitectureDemoStack/AWSPrivateNetwork/AWSVpcPrivateSubnetA/AWSVpcPrivateSubnetA
    Metadata:
      aws:cdk:path: CdkHybridArchitectureDemoStack/AWSPrivateNetwork/AWSVpcPrivateSubnetA/AWSVpcPrivateSubnetA/Subnet
  AWSPrivateNetworkAWSVpcPrivateSubnetBSubnet3881A3B2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: AWSPrivateNetworkAWSVpcE0F4E4E3
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: ""
      CidrBlock: 10.16.96.0/20
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: CdkHybridArchitectureDemoStack/AWSPrivateNetwork/AWSVpcPrivateSubnetB/AWSVpcPrivateSubnetB
    Metadata:
      aws:cdk:path: CdkHybridArchitectureDemoStack/AWSPrivateNetwork/AWSVpcPrivateSubnetB/AWSVpcPrivateSubnetB/Subnet
  AWSPrivateNetworkAWSVpcCustomRT54EBF452:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: AWSPrivateNetworkAWSVpcE0F4E4E3
      Tags:
        - Key: Name
          Value: custom_rt
    Metadata:
      aws:cdk:path: CdkHybridArchitectureDemoStack/AWSPrivateNetwork/AWSVpcCustomRT
  AWSPrivateNetworkAWSVpcTransitGatewayEDEF3642:
    Type: AWS::EC2::TransitGateway
    Properties:
      AmazonSideAsn: 64512
      DefaultRouteTableAssociation: enable
      Description: Transit Gateway for AWS private network
      DnsSupport: enable
      VpnEcmpSupport: enable
    Metadata:
      aws:cdk:path: CdkHybridArchitectureDemoStack/AWSPrivateNetwork/AWSVpcTransitGateway
  AWSPrivateNetworkAWSVpcTransitGatewayAttachment45E6BBDA:
    Type: AWS::EC2::TransitGatewayAttachment
    Properties:
      SubnetIds:
        - Ref: AWSPrivateNetworkAWSVpcPrivateSubnetASubnetC2333EDC
        - Ref: AWSPrivateNetworkAWSVpcPrivateSubnetBSubnet3881A3B2
      TransitGatewayId:
        Fn::GetAtt:
          - AWSPrivateNetworkAWSVpcTransitGatewayEDEF3642
          - Id
      VpcId:
        Ref: AWSPrivateNetworkAWSVpcE0F4E4E3
    Metadata:
      aws:cdk:path: CdkHybridArchitectureDemoStack/AWSPrivateNetwork/AWSVpcTransitGatewayAttachment
  AWSPrivateNetworkAWSVpcTGWDefaultRoute1918A414:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Fn::GetAtt:
          - AWSPrivateNetworkAWSVpcCustomRT54EBF452
          - RouteTableId
      DestinationCidrBlock: 0.0.0.0/0
      TransitGatewayId:
        Fn::GetAtt:
          - AWSPrivateNetworkAWSVpcTransitGatewayEDEF3642
          - Id
    DependsOn:
      - AWSPrivateNetworkAWSVpcTransitGatewayAttachment45E6BBDA
    Metadata:
      aws:cdk:path: CdkHybridArchitectureDemoStack/AWSPrivateNetwork/AWSVpcTGWDefaultRoute
  AWSPrivateNetworkAWSVpcPrivateSubnetARTAssociation1D0C4F53:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Fn::GetAtt:
          - AWSPrivateNetworkAWSVpcCustomRT54EBF452
          - RouteTableId
      SubnetId:
        Ref: AWSPrivateNetworkAWSVpcPrivateSubnetASubnetC2333EDC
    Metadata:
      aws:cdk:path: CdkHybridArchitectureDemoStack/AWSPrivateNetwork/AWSVpcPrivateSubnetARTAssociation
  AWSPrivateNetworkAWSVpcPrivateSubnetBRTAssociation2D0B469E:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Fn::GetAtt:
          - AWSPrivateNetworkAWSVpcCustomRT54EBF452
          - RouteTableId
      SubnetId:
        Ref: AWSPrivateNetworkAWSVpcPrivateSubnetBSubnet3881A3B2
    Metadata:
      aws:cdk:path: CdkHybridArchitectureDemoStack/AWSPrivateNetwork/AWSVpcPrivateSubnetBRTAssociation
  AWSPrivateNetworkAWSVpcEC2SecurityGroupC40A969A:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: AWS private network default security group
      GroupName: aws-vpc-ec2A-sg
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          Description: Allow SSH IPv4 IN
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
        - CidrIp: 192.168.8.0/21
          Description: Allow ALL from ONPREM Networks
          IpProtocol: "-1"
        - CidrIp:
            Fn::GetAtt:
              - AWSPrivateNetworkAWSVpcE0F4E4E3
              - CidrBlock
          Description:
            Fn::Join:
              - ""
              - - "from "
                - Fn::GetAtt:
                    - AWSPrivateNetworkAWSVpcE0F4E4E3
                    - CidrBlock
                - :443
          FromPort: 443
          IpProtocol: tcp
          ToPort: 443
      VpcId:
        Ref: AWSPrivateNetworkAWSVpcE0F4E4E3
    Metadata:
      aws:cdk:path: CdkHybridArchitectureDemoStack/AWSPrivateNetwork/AWSVpcEC2SecurityGroup/Resource
  AWSPrivateNetworkAWSVpcEC2SecurityGroupSelfReferenceRule68197218:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: "-1"
      GroupId:
        Fn::GetAtt:
          - AWSPrivateNetworkAWSVpcEC2SecurityGroupC40A969A
          - GroupId
      SourceSecurityGroupId:
        Fn::GetAtt:
          - AWSPrivateNetworkAWSVpcEC2SecurityGroupC40A969A
          - GroupId
    Metadata:
      aws:cdk:path: CdkHybridArchitectureDemoStack/AWSPrivateNetwork/AWSVpcEC2SecurityGroupSelfReferenceRule
  AWSPrivateNetworkAWSVpcEC2MessagesInterfaceEndpointFED86BC8:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: com.amazonaws.us-east-1.ec2messages
      VpcId:
        Ref: AWSPrivateNetworkAWSVpcE0F4E4E3
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - Fn::GetAtt:
            - AWSPrivateNetworkAWSVpcEC2SecurityGroupC40A969A
            - GroupId
      SubnetIds: []
      VpcEndpointType: Interface
    Metadata:
      aws:cdk:path: CdkHybridArchitectureDemoStack/AWSPrivateNetwork/AWSVpcEC2MessagesInterfaceEndpoint/Resource
  AWSPrivateNetworkAWSVpcSSMMessagesInterfaceEndpoint9B83740B:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: com.amazonaws.us-east-1.ssmmessages
      VpcId:
        Ref: AWSPrivateNetworkAWSVpcE0F4E4E3
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - Fn::GetAtt:
            - AWSPrivateNetworkAWSVpcEC2SecurityGroupC40A969A
            - GroupId
      SubnetIds: []
      VpcEndpointType: Interface
    Metadata:
      aws:cdk:path: CdkHybridArchitectureDemoStack/AWSPrivateNetwork/AWSVpcSSMMessagesInterfaceEndpoint/Resource
  AWSPrivateNetworkAWSVpcSSMInterfaceEndpointE85AB325:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: com.amazonaws.us-east-1.ssm
      VpcId:
        Ref: AWSPrivateNetworkAWSVpcE0F4E4E3
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - Fn::GetAtt:
            - AWSPrivateNetworkAWSVpcEC2SecurityGroupC40A969A
            - GroupId
      SubnetIds: []
      VpcEndpointType: Interface
    Metadata:
      aws:cdk:path: CdkHybridArchitectureDemoStack/AWSPrivateNetwork/AWSVpcSSMInterfaceEndpoint/Resource
  AWSPrivateNetworkAWSVpcEC2RoleE08C7582:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
        Version: "2012-10-17"
      Path: /
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - ec2messages:AcknowledgeMessage
                  - ec2messages:DeleteMessage
                  - ec2messages:FailMessage
                  - ec2messages:GetEndpoint
                  - ec2messages:GetMessages
                  - ec2messages:SendReply
                  - s3:*
                  - sns:*
                  - ssm:DescribeAssociation
                  - ssm:DescribeDocument
                  - ssm:GetDeployablePatchSnapshotForInstance
                  - ssm:GetDocument
                  - ssm:GetManifest
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:ListAssociations
                  - ssm:ListInstanceAssociations
                  - ssm:PutComplianceItems
                  - ssm:PutConfigurePackageResult
                  - ssm:PutInventory
                  - ssm:UpdateAssociationStatus
                  - ssm:UpdateInstanceAssociationStatus
                  - ssm:UpdateInstanceInformation
                  - ssmmessages:CreateControlChannel
                  - ssmmessages:CreateDataChannel
                  - ssmmessages:OpenControlChannel
                  - ssmmessages:OpenDataChannel
                Effect: Allow
                Resource: "*"
            Version: "2012-10-17"
          PolicyName: root
      RoleName: aws-vpc-ec2-iam-role
    Metadata:
      aws:cdk:path: CdkHybridArchitectureDemoStack/AWSPrivateNetwork/AWSVpcEC2Role/Resource
  AWSPrivateNetworkAWSVpcEC2InstanceProfileE272E475:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: AWSPrivateNetworkAWSVpcEC2RoleE08C7582
      Path: /
    Metadata:
      aws:cdk:path: CdkHybridArchitectureDemoStack/AWSPrivateNetwork/AWSVpcEC2InstanceProfile
  AWSPrivateNetworkAWSVpcEC2AInstanceProfile8B4C9E39:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: []
    Metadata:
      aws:cdk:path: CdkHybridArchitectureDemoStack/AWSPrivateNetwork/AWSVpcEC2A/InstanceProfile
  AWSPrivateNetworkAWSVpcEC2A51641361:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      IamInstanceProfile:
        Ref: AWSPrivateNetworkAWSVpcEC2AInstanceProfile8B4C9E39
      ImageId:
        Ref: SsmParameterValueawsserviceamiamazonlinuxlatestamznamihvmx8664gp2C96584B6F00A464EAD1953AFF4B05118Parameter
      InstanceType: t2.micro
      SecurityGroupIds:
        - Fn::GetAtt:
            - AWSPrivateNetworkAWSVpcEC2SecurityGroupC40A969A
            - GroupId
      SubnetId:
        Ref: AWSPrivateNetworkAWSVpcPrivateSubnetASubnetC2333EDC
      Tags:
        - Key: Name
          Value: aws-vpc-ec2a
      UserData:
        Fn::Base64: "#!/bin/bash"
    DependsOn:
      - AWSPrivateNetworkAWSVpcEC2InstanceProfileE272E475
    Metadata:
      aws:cdk:path: CdkHybridArchitectureDemoStack/AWSPrivateNetwork/AWSVpcEC2A/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/31PwWrDMAz9lt4dr+tYYcdSRsktJKXXorjKqjaRgy1TQsi/z02W5TDYSXpPeu9JG7191+sVPHxiLvekplL3hYC5q0idezQb3Z9ao/YVn7K9KkLJKE+0dLkNgkcoa3yiowP2JAcQfED3l9lJdL82yIt2sVusdt5bQyBkWRVogiPpDs6Gdlz+l0j5y6H3KmVBV4HBeP8nX1pLU2b84xem7AXYjCfM/aAIGt3ndnporvM4c7aiGodB5ehtcJM4AwcNxsBR8jMYVNbJ1fLLm35d64/VzRMlLrBQgzqf6jeB4tYxgQEAAA==
    Metadata:
      aws:cdk:path: CdkHybridArchitectureDemoStack/CDKMetadata/Default
Parameters:
  SsmParameterValueawsserviceamiamazonlinuxlatestamznamihvmx8664gp2C96584B6F00A464EAD1953AFF4B05118Parameter:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn-ami-hvm-x86_64-gp2
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

